---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: k8s-storage
provisioner: linstor.csi.linbit.com
parameters:  
  linstor.csi.linbit.com/placementCount: "2"
  linstor.csi.linbit.com/storagePool: "k8s-storage"
  linstor.csi.linbit.com/allowRemoteVolumeAccess: "true"
  property.linstor.csi.linbit.com/DrbdOptions/auto-quorum: suspend-io
  property.linstor.csi.linbit.com/DrbdOptions/Resource/on-no-data-accessible: suspend-io
  property.linstor.csi.linbit.com/DrbdOptions/Resource/on-suspended-primary-outdated: force-secondary
  property.linstor.csi.linbit.com/DrbdOptions/Net/rr-conflict: retry-connect
  
volumeBindingMode: Immediate
allowVolumeExpansion: true